language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI Run Alert Email
notifications:
  email:
    recipients:
      - nkw9986@gmail.com