language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r spring-boot-start *
  - mkdir -p deploy
  - mv spring-boot-start.zip deploy/spring-boot-start.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: boot-start-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: boot-start-build
    key: spring-boot-start.zip
    bundle_type: zip
    application: boot-start
    deployment_group: boot-start-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI Run Alert Email
notifications:
  email:
    recipients:
      - nkw9986@gmail.com