spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "Your Google Cloud Client Id"
            client-secret: "Your Google Cloud Client Secret Key"
            scope: profile,email
          naver:
            client-id: "Your Naver Application Id"
            client-secret: "Your Naver Application Secret Key"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: "authorization_code"
            scope: "name,email,profile_image"
            client-name: "Naver"
        provider:
          naver:
            authorization_uri: "https://nid.naver.com/oauth2.0/authorize"
            token_uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user_name_attribute: "response"